Tagging post release branch as 3.4.2.1 (3.4.2 with backported bug fix and unittest2 support).

diff --git a/bin/run-escript b/bin/run-escript
--- a/bin/run-escript
+++ b/bin/run-escript
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Escript/Finley wrapper for python
 # Sets LD_LIBRARY_PATH and PYTHONPATH and then runs either python or the MPI launcher
@@ -17,7 +17,7 @@ STDLOCATION=0
 #Now we find the location of this script
 #Note that this location should be absolute but does not need to be unique
 scriptdir=""
-CURDIR=$(pwd)
+CURDIR=`pwd`
 
 #Environment vars which control operations:
 # ESCRIPT_NUM_NODES, ESCRIPT_NUM_PROCS, ESCRIPT_NUM_THREADS, ESCRIPT_HOSTFILE, ESCRIPT_CREATESTDFILES
@@ -32,27 +32,27 @@ then
 else
   # We don't know the escript root so we need to work it out from the invocation
   # Need to match if the name contains /
-  if $(echo $0|grep -q /)
+  if [[ $0 =~ / ]]
   then
       # We are not using the PATH to find the script
-      cd "$(dirname $0)"
-      scriptdir=$(pwd)
+      cd "`dirname $0`"
+      scriptdir=`pwd`
       cd "$CURDIR"
   else
-      # name does not contain / therefore we are using
-      tscriptdir=$(which $0)
+      # name does not contain / therefore we are using 
+      tscriptdir=`which $0`
       if [ $? -ne 0 ]
       then
           echo "Error! Unable to determine script directory. Exiting."
           exit 1
       fi
-      scriptdir=$(dirname $tscriptdir)
+      scriptdir=`dirname $tscriptdir`
   fi
 
   cd "$scriptdir/.."
-  ESCRIPT_ROOT=$(pwd)
+  ESCRIPT_ROOT=`pwd`
   cd ..
-  ESCRIPT_PARENT=$(pwd)
+  ESCRIPT_PARENT=`pwd`
   cd "$CURDIR"
 
 fi
@@ -97,10 +97,10 @@ if [ ! -r "$BUILDINFO_FILE" ]; then
         echo "export LD_LIBRARY_PATH=$EXTRA_LD_LIBRARY_PATH:\$LD_LIBRARY_PATH"
         echo "export PYTHONPATH=$EXTRA_PYTHONPATH:\$PYTHONPATH"
         echo "export PATH=$EXTRA_PATH:\$PATH"
-        if [ "$(uname)" = "Darwin" ]
+        if [ "`uname`" = "Darwin" ]
         then
             echo "export DYLD_LIBRARY_PATH=$EXTRA_DYLD_LIBRARY_PATH:$EXTRA_LD_LIBRARY_PATH:\$DYLD_LIBRARY_PATH"
-        fi
+        fi  
         exit 0
     fi
     echo "Error! Unable to read escript build information. Exiting."
@@ -108,17 +108,17 @@ if [ ! -r "$BUILDINFO_FILE" ]; then
 fi
 
 get_buildvar () {
-    echo $(grep "^$1=" "$BUILDINFO_FILE" |cut -d= -f2)
+    echo `grep "^$1=" "$BUILDINFO_FILE" |cut -d= -f2`
 }
 
 #
 #   Add VisIt paths if required
 #
-WITH_VISIT=$(get_buildvar visit)
+WITH_VISIT=`get_buildvar visit`
 if [ "$WITH_VISIT" = "1" ]; then
-    VISIT_BIN=$(which visit 2>/dev/null)
+    VISIT_BIN=`which visit 2>/dev/null`
     if [ $? -eq 0 ]; then
-        VISIT_PY_PATH=$($VISIT_BIN -env | grep LIBPATH | cut -d= -f2)
+        VISIT_PY_PATH=`$VISIT_BIN -env | grep LIBPATH | cut -d= -f2`
         EXTRA_PYTHONPATH=$EXTRA_PYTHONPATH:$VISIT_PY_PATH
         EXTRA_LD_LIBRARY_PATH=$EXTRA_LD_LIBRARY_PATH:$VISIT_PY_PATH
     elif [ ! -z $ESCRIPT_VERBOSE ]; then
@@ -134,7 +134,7 @@ Usage: run-escript [options] script.py [arguments...]
 	-f file		name of MPI hostfile
 	-c		print compile information for escript and exit
 	-V		print escript version and exit
-	-i		interactive mode
+	-i		interactive mode 
 	-b		do not invoke python (run non-python programs)
 	-e		print export statements for environment and exit
 	-o		redirect output from MPI to files
@@ -170,7 +170,7 @@ do
       "c")  cat "$BUILDINFO_FILE"
         exit 0
         ;;
-      "V")  echo "escript-development(build "$(get_buildvar svn_revision)")"
+      "V")  echo "escript-development(build "`get_buildvar svn_revision`")"
         exit 0
         ;;
       "h")  echo "$HELP_TEXT"
@@ -181,7 +181,7 @@ do
       "e")  echo "export LD_LIBRARY_PATH=$EXTRA_LD_LIBRARY_PATH:\$LD_LIBRARY_PATH"
         echo "export PYTHONPATH=$EXTRA_PYTHONPATH:\$PYTHONPATH"
         echo "export PATH=$EXTRA_PATH:\$PATH"
-        if [ "$(uname)" = "Darwin" ]
+        if [ "`uname`" = "Darwin" ]
         then
             echo "export DYLD_LIBRARY_PATH=$EXTRA_DYLD_LIBRARY_PATH:$EXTRA_LD_LIBRARY_PATH:\$DYLD_LIBRARY_PATH"
         fi
@@ -198,13 +198,13 @@ do
         ;;
     esac
 done
-shift $(($OPTIND - 1))
+shift `expr $OPTIND - 1`
 #==============================================
 #
 #   Read MPI_FLAVOUR and WITH_OPENMP from the buildvars
 #
-MPI_FLAVOUR=$(get_buildvar mpi)
-WITH_OPENMP=$(get_buildvar openmp)
+MPI_FLAVOUR=`get_buildvar mpi`
+WITH_OPENMP=`get_buildvar openmp`
 
 if [ ! -z $ESCRIPT_VERBOSE ]; then
     echo "MPI flavour is $MPI_FLAVOUR."
@@ -218,13 +218,13 @@ export PATH=$EXTRA_PATH:$PATH
 export LD_LIBRARY_PATH=$EXTRA_LD_LIBRARY_PATH:$LD_LIBRARY_PATH
 export PYTHONPATH=$EXTRA_PYTHONPATH:$PYTHONPATH
 EXPORT_ENV="PATH,LD_LIBRARY_PATH,PYTHONPATH"
-if [ "$(uname)" = "Darwin" ]
+if [ "`uname`" = "Darwin" ]
 then
     export DYLD_LIBRARY_PATH=$EXTRA_DYLD_LIBRARY_PATH:$EXTRA_LD_LIBRARY_PATH:$DYLD_LIBRARY_PATH
     EXPORT_ENV="$EXPORT_ENV,DYLD_LIBRARY_PATH"
 fi
-if [ ! -z $ESCRIPT_VERBOSE ]
-then
+if [ ! -z $ESCRIPT_VERBOSE ] 
+then 
     echo "PATH = $PATH "
     echo "LD_LIBRARY_PATH = $LD_LIBRARY_PATH "
     echo "PYTHONPATH = $PYTHONPATH "
@@ -234,7 +234,7 @@ fi
 #
 #  Ensure the variables have sensible values
 #
-if [ "$MPI_FLAVOUR" = "none" ]
+if [ "$MPI_FLAVOUR" = "none" ] 
 then
     if [ ! -z "$ESCRIPT_NUM_NODES" ]; then
         if [ $ESCRIPT_NUM_NODES -gt 1 ]; then
@@ -259,13 +259,13 @@ else
         ESCRIPT_HOSTFILE=$PBS_NODEFILE
     fi
 
-    if [ ! -z "$ESCRIPT_HOSTFILE" ]
+    if [ ! -z "$ESCRIPT_HOSTFILE" ] 
     then
         if [ -f "$ESCRIPT_HOSTFILE" ]
         then
             cat "$ESCRIPT_HOSTFILE" | sort -u > $HOSTFILE
-            NUM_HOSTS=$(cat "$HOSTFILE" | wc -l)
-            if [ ! -z $ESCRIPT_NUM_NODES ]
+            NUM_HOSTS=`cat "$HOSTFILE" | wc -l`
+            if [ ! -z $ESCRIPT_NUM_NODES ] 
             then
                 if [ $NUM_HOSTS -ne $ESCRIPT_NUM_NODES ]
                 then
@@ -294,7 +294,7 @@ else
     fi
 
     if [ ! -z $ESCRIPT_VERBOSE ]
-    then
+    then 
         echo "ESCRIPT_NUM_NODES = $ESCRIPT_NUM_NODES "
         echo "ESCRIPT_NUM_PROCS = $ESCRIPT_NUM_PROCS "
     fi
@@ -325,7 +325,7 @@ fi
 # Now we compute total number of Processes
 #
 TOTPROC=$((ESCRIPT_NUM_NODES * ESCRIPT_NUM_PROCS))
-if [ $? -ne 0 ]     #Some compute error
+if [ $? -ne 0 ]     #Some compute error 
 then            #This could happen if the args were not a number
     echo "expression of total number of processors = $ESCRIPT_NUM_NODES * $ESCRIPT_NUM_PROCS is not numerical."
     exit 1
@@ -340,7 +340,7 @@ then
     exit 1
 fi
 
-if [ $TOTPROC -gt 1 ]
+if [ $TOTPROC -gt 1 ] 
 then
     if [ "$ESCRIPT_CREATESTDFILES" = "y" ]
     then
@@ -375,12 +375,11 @@ fi
 
 if [ ! -z "$DO_VALGRIND" ]
 then
-    VALGRIND_BIN=$(which valgrind 2>/dev/null)
+    VALGRIND_BIN=`which valgrind 2>/dev/null`
     if [ $? -eq 0 ]; then
         LOGDIR=$ESCRIPT_ROOT/valgrind_logs
         [ -d $LOGDIR ] || mkdir $LOGDIR
-        VG_TOOL=$(echo $DO_VALGRIND | awk '{ s=substr($0,1,1);print s;}')
-        if [ $VG_TOOL = "c" ];
+        if [ ${DO_VALGRIND:0:1} = "c" ];
         then
             # run callgrind
             LOGFILE=${LOGDIR}/callgrind.%p.xml
@@ -388,8 +387,8 @@ then
             EXEC_CMD="$EXEC_CMD $VALGRIND"
         else
             # run memcheck by default
-            LAST_N=$(ls -1 $LOGDIR|grep "^memcheck"|tail -1|cut -d. -f2)
-            NEW_N=$(printf "%04d" $((LAST_N + 1)))
+            LAST_N=`ls -1 $LOGDIR|grep "^memcheck"|tail -1|cut -d. -f2`
+            NEW_N=`printf "%04d" $((10#$LAST_N + 1))`
             LOGFILE=${LOGDIR}/memcheck.${NEW_N}.xml
             VALGRIND="valgrind --tool=memcheck --xml=yes --show-reachable=yes --error-limit=no --gen-suppressions=all --suppressions=$ESCRIPT_ROOT/scripts/escript.supp --leak-check=full --xml-file=$LOGFILE"
             EXEC_CMD="$EXEC_CMD $VALGRIND"
@@ -406,9 +405,9 @@ then
 else
     # Check to see if the python version we were compiled with matches the
     # one of PYTHON_CMD.
-    compfull=$(get_buildvar python_version)
-    compversion=$(echo $compfull | cut -d. -f1,2)
-    compmajor=$(echo $compfull | cut -d. -f1)
+    compfull=`get_buildvar python_version`
+    compversion=`echo $compfull | cut -d. -f1,2`
+    compmajor=`echo $compfull | cut -d. -f1`
     if [ "$PYTHON_CMD" = "python" ] # if people have customised the command they
     then                                # might not want us changing it
         if [ "$compmajor" = "3" ]
@@ -416,7 +415,7 @@ else
             PYTHON_CMD=python3
         fi
     fi
-    intversion=$($PYTHON_CMD -c 'from __future__ import print_function;import sys;print("%d.%d"%(sys.version_info[0], sys.version_info[1]))')
+    intversion=`$PYTHON_CMD -c 'from __future__ import print_function;import sys;print("%d.%d"%(sys.version_info[0], sys.version_info[1]))'`
     if [ "$compversion" != "$intversion" ]
     then
         echo "Python versions do not match. Escript was compiled for "$compversion"."
@@ -452,21 +451,20 @@ then
 fi
 EXIT_CODE=1
 #=============== no MPI ===================================
-if [ "$MPI_FLAVOUR" = "none" ]
+if [ "$MPI_FLAVOUR" = "none" ] 
 then
-   $EXEC_CMD
+   $EXEC_CMD 
    EXIT_CODE=$?
 #=============== OpenMPI ===================================
-elif [ "$MPI_FLAVOUR" = "OPENMPI" ]
-then
-   EXPORT_ENV=$(echo $EXPORT_ENV|sed -e 's/,/ -x /g')
-   if [ ! -z "$HOSTFILE" ]
+elif [ "$MPI_FLAVOUR" = "OPENMPI" ] 
+then 
+   if [ ! -z "$HOSTFILE" ] 
    then
-      HOST_LIST=$(sort -u "$HOSTFILE" | awk 'BEGIN{S=""}{if (S == "") { S = $0 } else {S = S "," $0}}END{print S}')
-      CMD="mpirun --gmca mpi_warn_on_fork 0 -x ${EXPORT_ENV} --bynode --bind-to-none --host $HOST_LIST -np $TOTPROC $EXEC_CMD"
+      HOST_LIST=`sort -u "$HOSTFILE" | awk 'BEGIN{S=""}{if (S == "") { S = $0 } else {S = S "," $0}}END{print S}'`
+      CMD="mpirun --gmca mpi_warn_on_fork 0 -x ${EXPORT_ENV//,/ -x } --bynode --bind-to-none --host $HOST_LIST -np $TOTPROC $EXEC_CMD"
    else
-      CMD="mpirun --gmca mpi_warn_on_fork 0 -x ${EXPORT_ENV} --cpus-per-rank $ESCRIPT_NUM_THREADS -np $TOTPROC $EXEC_CMD"
-   fi
+      CMD="mpirun --gmca mpi_warn_on_fork 0 -x ${EXPORT_ENV//,/ -x } --cpus-per-rank $ESCRIPT_NUM_THREADS -np $TOTPROC $EXEC_CMD"
+   fi 
    if [ ! -z $ESCRIPT_VERBOSE ]; then echo "MPI command is \"$CMD\"."; fi
    $CMD
    EXIT_CODE=$?
@@ -478,68 +476,84 @@ then
    if [ "$WITH_OPENMP" = "1" ]
    then
        export I_MPI_PIN_DOMAIN=omp
-       EXPORT_ENV="$EXPORT_ENV,I_MPI_PIN_DOMAIN"
+       EXPORT_ENV="$EXPORT_ENV, I_MPI_PIN_DOMAIN"
    fi
 
-   if [ ! -z "$HOSTFILE" ]
+   if [ ! -z "$HOSTFILE" ] 
    then
-        CMD="mpirun -hostfile $HOSTFILE -n $TOTPROC -ppn $ESCRIPT_NUM_PROCS $EXEC_CMD"
+      mpdboot -n $ESCRIPT_NUM_NODES -r ssh -f "$HOSTFILE"
+      if [ $? -ne 0 ] 
+      then
+         echo "mpdboot with host file $ESCRIPT_HOSTFILE for $ESCRIPT_NUM_NODES nodes failed."
+         exit 1
+      else 
+          if [ ! -z $ESCRIPT_VERBOSE ]; then echo "mpdboot was started with host file $ESCRIPT_HOSTFILE for $ESCRIPT_NUM_NODES nodes."; fi
+      fi
    else
-        if [ ! -z $ESCRIPT_VERBOSE ]; then echo "Empty hostfile, running on single node"; fi
-        CMD="mpirun -n 1 -ppn $ESCRIPT_NUM_PROCS $EXEC_CMD"
+      mpdboot -n 1 -r ssh 
+      if [ $? -ne 0 ] 
+      then
+         echo "mpdboot failed."
+         exit 1
+      else 
+          if [ ! -z $ESCRIPT_VERBOSE ]; then echo "mpdboot was started."; fi
+      fi
    fi
+   CMD="mpiexec -perhost $ESCRIPT_NUM_PROCS -envall -n $TOTPROC $EXEC_CMD"
    if [ ! -z $ESCRIPT_VERBOSE ]; then echo "MPI command is \"$CMD\"."; fi
    $CMD
    EXIT_CODE=$?
+   mpdallexit
+   if [ ! -z $ESCRIPT_VERBOSE ]; then echo "mpdallexit executed."; fi
 #=============== SGI's MPIMPT ===================================
 elif [ "$MPI_FLAVOUR" = "MPT" ]
 then
    export MPI_NUM_MEMORY_REGIONS=0
    EXPORT_ENV="$EXPORT_ENV,MPI_NUM_MEMORY_REGIONS"
-   if [ ! -z "$HOSTFILE" ]
+   if [ ! -z "$HOSTFILE" ] 
    then
-      HOST_LIST=$(awk 'BEGIN{S=""}{if (S == "") { S = $0 } else {S = S "," $0}}END{print S}' "$HOSTFILE")
+      HOST_LIST=`awk 'BEGIN{S=""}{if (S == "") { S = $0 } else {S = S "," $0}}END{print S}' "$HOSTFILE"`
       CMD="mpirun $HOST_LIST -np $ESCRIPT_NUM_PROCS $EXEC_CMD"
    else
       CMD="mpirun -np $TOTPROC $EXEC_CMD"
-   fi
+   fi 
    if [ ! -z $ESCRIPT_VERBOSE ]; then echo "MPI command is \"$CMD\"."; fi
    $CMD
    EXIT_CODE=$?
 #=============== MPICH ===================================
 elif [ "$MPI_FLAVOUR" = "MPICH" ]
 then
-   if [ ! -z "$HOSTFILE" ]
+   if [ ! -z "$HOSTFILE" ] 
    then
       touch "$HOSTFILE2"
-      for i in $(seq $ESCRIPT_NUM_PROCS); do cat "$HOSTFILE" >> "$HOSTFILE2"; done
-      CMD="mpirun -machinefile \"$HOSTFILE2\" -np $TOTPROC $EXEC_CMD"
+      for (( i=1;i<=$ESCRIPT_NUM_PROCS;i+=1 )) ; do cat "$HOSTFILE" >> "$HOSTFILE2"  ; done
+      CMD="mpirun -machinefile \"$HOSTFILE2\"  -np $TOTPROC $EXEC_CMD"
    else
       CMD="mpirun -np $TOTPROC $EXEC_CMD"
-   fi
+   fi 
    if [ ! -z $ESCRIPT_VERBOSE ]; then echo "MPI command is \"$CMD\"."; fi
    $CMD
    EXIT_CODE=$?
 #=============== MPICH2 ===================================
 elif [ "$MPI_FLAVOUR" = "MPICH2" ]
 then
-   if [ ! -z "$HOSTFILE" ]
+   if [ ! -z "$HOSTFILE" ] 
    then
          mpdboot -n $ESCRIPT_NUM_NODES -r ssh -f "$HOSTFILE"
-         if [ $? -ne 0 ]
+         if [ $? -ne 0 ] 
          then
             echo "mpdboot with host file $ESCRIPT_HOSTFILE for $ESCRIPT_NUM_NODES nodes failed."
             exit 1
-         else
-             if [ ! -z $ESCRIPT_VERBOSE ]; then echo "mpdboot was started with host file $HOSTFILE for $ESCRIPT_NUM_NODES nodes."; fi
+         else 
+             if [ ! -z $ESCRIPT_VERBOSE ]; then echo "mpdboot was started with host file $ESCRIPT_HOSTFILE for $ESCRIPT_NUM_NODES nodes."; fi
          fi
    else
-      mpdboot -n 1 -r ssh
-      if [ $? -ne 0 ]
+      mpdboot -n 1 -r ssh 
+      if [ $? -ne 0 ] 
       then
          echo "mpdboot failed."
          exit 1
-      else
+      else 
           if [ ! -z $ESCRIPT_VERBOSE ]; then echo "mpdboot was started."; fi
       fi
    fi
@@ -552,10 +566,5 @@ then
 else
    echo "unknown MPI flavour '$MPI_FLAVOUR'."
 fi
-
-if [ ! -z "$DO_VALGRIND" ]; then
-   echo "Valgrind log file written to ${LOGFILE}"
-fi
-
 exit $EXIT_CODE
 
