Made it easier to glance at the logs and see which runs failed

diff --git a/autotest-scons b/autotest-scons
--- a/autotest-scons
+++ b/autotest-scons
@@ -66,19 +66,24 @@ echo ""
 START=\`date '+%Y/%m/%d %H:%M'\`
 
 finish () {
+  # state will be 'FAILURE' or 'SUCCESS'
+  state="\$1"
   date
   # Clean up the sandbox
   cd $WorkDir
   /bin/rm -rf sandbox.$RunDate
   END=\`date '+%Y/%m/%d %H:%M'\`
-  cat << END_MSG | mail -s "ESYS_TESTS $target $RunDate \$1" $MAIL_RECIPIENTS
+  cat << END_MSG | mail -s "ESYS_TESTS $target $RunDate \$state" $MAIL_RECIPIENTS
 \$2.
 The tests ran from \$START to \$END on \$NCPUS CPUs
 See the log files in $WorkDir/Logs/$RunDate*
 This mail was sent by $SCRIPT_NAME
 running as \$USER on \`hostname\`.
 END_MSG
-  test "x\$1" = "FAILURE" && exit 1
+  if [ "x\$state" = "xFAILURE" ]; then
+    touch Logs/$RunDate.FAILURE
+    exit 1
+  fi
   exit 0
 }
 
@@ -116,8 +121,8 @@ scons -j \$NCPUS $target >> $out_file 2>&1		|| finish FAILURE "Could not run sco
 
 echo "Cleaning up after the tests"
 
-# Delete files older than 21 days
-find $WorkDir -atime +21 -exec rm -f {} \;
+# Delete files older than 60 days
+find $WorkDir -atime +60 -exec rm -f {} \;
 
 finish SUCCESS "Successfully ran 'scons $target' on \`hostname\`"
 
