Fixes to account for differing versions of netcdf

diff --git a/packaging/debuntu/builddeb b/packaging/debuntu/builddeb
--- a/packaging/debuntu/builddeb
+++ b/packaging/debuntu/builddeb
@@ -79,8 +79,16 @@ then
     exit 8
 fi
 
-echo "Python package is $PYPKG."
+NCDF=`dpkg --get-selections 'libnetcdf?*' | grep install | grep -v '-' | cut -f1`
+if [ `echo $NCDF | wc -w ` != "1" ]
+then
+    echo "Can't determine the version of netcdf"
+    exit 8
+fi
 
+
+echo "Python package is $PYPKG."
+echo "netcdf version is $NCDF."
 BOOSTPKG=`dpkg --get-selections 'libboost-python?????*' | grep -v 'de' | grep 'install' | cut -f1`
 if [ `echo $BOOSTPKG | wc -w` != "1" ]
 then
@@ -145,6 +153,7 @@ sed -e "s%STDLOCATION=0%STDLOCATION=1%" < $SRCDIR/bin/$WRAPPERNAME > $BINOUT/$WR
 
 sed -i -e "s%PYPKG%$PYPKG%" $OUTPUTROOT/DEBIAN/control
 sed -i -e "s%BOOSTPKG%$BOOSTPKG%" $OUTPUTROOT/DEBIAN/control
+sed -i -e "s%NETCDFPKG%$NCDF%" $OUTPUTROOT/DEBIAN/control
 
 
 # if [ -z "$needalt" ]
