temporary unit tests scripts

diff --git a/trunk/autotest-scons b/trunk/autotest-scons
--- a/trunk/autotest-scons
+++ b/trunk/autotest-scons
@@ -28,32 +28,56 @@ then
   exit 2
 fi
 
-echo running svn update
-svn update
-if [ $? != 0 ]
-then
-  echo svn update failed
-  echo "svn update failed" | mail -s "esys autotest results" $MAIL_RECIPIENTS
-  exit 3
-fi
-
-echo running scons debug=1
-scons debug=1
-if [ $? != 0 ]
-then
-  echo scons failed
-  echo "scons failed - see autotest logfile" | mail -s "esys autotest results" $MAIL_RECIPIENTS
-  exit 5
-fi
-
-#echo running mk unit_test
-#./mk unit_test
+#echo running svn update
+#svn update
 #if [ $? != 0 ]
 #then
-#  echo ./mk unit_test failed
-#  echo "./mk unit_test failed - see autotest logfile" | mail -s "esys autotest results" $MAIL_RECIPIENTS
-#  exit 6
+#  echo svn update failed
+#  echo "svn update failed" | mail -s "esys autotest results" $MAIL_RECIPIENTS
+#  exit 3
 #fi
+##
+#echo running scons debug=1
+#scons debug=1
+#if [ $? != 0 ]
+#then
+#  echo scons failed
+#  echo "scons failed - see autotest logfile" | mail -s "esys autotest results" $MAIL_RECIPIENTS
+#  exit 5
+#fi
+
+echo running bruce unit_tests
+cd bruce/test
+./unit_test
+if [ $? != 0 ]
+then
+  echo bruce unit_test failed
+  echo "bruce unit_test failed - see autotest logfile" | mail -s "esys autotest results" $MAIL_RECIPIENTS
+  exit 6
+fi
+cd ..
+
+echo running escript unit_tests
+cd escript/test
+./unit_test
+if [ $? != 0 ]
+then
+  echo escript unit_test failed
+  echo "escript unit_test failed - see autotest logfile" | mail -s "esys autotest results" $MAIL_RECIPIENTS
+  exit 6
+fi
+cd ..
+
+echo running finley unit_tests
+cd finley/test
+./unit_test
+if [ $? != 0 ]
+then
+  echo finley unit_test failed
+  echo "finley unit_test failed - see autotest logfile" | mail -s "esys autotest results" $MAIL_RECIPIENTS
+  exit 6
+fi
+cd ..
 
 #echo running mk py_test
 #./mk py_test
