+ Merge of intelc_win32 branch (revision 741:755) with trunk. Tested on iVEC altix (run_tests and py_tests all pass)

diff --git a/trunk/autotest-scons b/trunk/autotest-scons
--- a/trunk/autotest-scons
+++ b/trunk/autotest-scons
@@ -1,129 +1,114 @@
-#!/bin/sh
-
-#
-# Submit a PBS job to run the tests
-#
-#	Usage: autotest-scons		# Short testing, only C++ tests
-#	Usage: autotest-scons run_tests	# Short testing, only C++ tests
-#	Usage: autotest-scons all_tests	# Long testing, C++ and python tests
-#
-# Copy this somewhere and run it every day via cron
-#
-# This file should be maintained in SVN as esys13/trunk/autotest-scons,
-# be sure to copy it there and commit after modification
-#
-
-# TODO: should try using the entire node: scons -j $NCPUS all_tests
-# I've been told this produces poor results...why?
-
-# Which tests should we run?
-target='run_tests'	# Default scons target that runs the tests
-test "x$1" != "x" && target="$1"
-
-MAIL_RECIPIENTS="gross@esscc.uq.edu.au elspeth@esscc.uq.edu.au matt@esscc.uq.edu.au robert.woodcock@csiro.au Peter.Hornby@csiro.au k.steube@uq.edu.au"
-# MAIL_RECIPIENTS="k.steube@uq.edu.au"
-
-RunDate=`date '+%Y_%m_%d'`	# Time stamp for log file names
-
-WorkDir=/raid3/ksteube/AutoTests
-cd $WorkDir
-
-# Where to put the output of scons run_tests
-out_file="$WorkDir/Logs/$RunDate.test.output"
-
-# Save the name of this script
-SCRIPT_NAME=$0
-
-# Below here \$variable means I want the variable interpreted when PBS runs the job, not when the job is submitted
-# Similarly for \`...\`
-
-# Write the PBS script to run the tests
-cat << EOF > Logs/$RunDate.pbs.script.sh
 #!/bin/bash
+#          Copyright 2006 by ACcESS MNRF
+#
+#              http://www.access.edu.au
+#       Primary Business: Queensland, Australia
+#  Licensed under the Open Software License version 3.0
+#     http://www.opensource.org/licenses/osl-3.0.php
+#
+#
+#
+# $Id: autotest-scons 162 2005-11-11 00:09:59Z svn $
+# An explicit testing script for esys using the scons build system
 
-#PBS -q q1
-#PBS -l ncpus=2
-#PBS -o $RunDate.pbs.stdout
-#PBS -e $RunDate.pbs.stderr
+# list of users to email test results to
+# currently disabled during testing.
+# MAIL_RECIPIENTS="gross@esscc.uq.edu.au elspeth@esscc.uq.edu.au matt@esscc.uq.edu.au robert.woodcock@csiro.au Peter.Hornby@csiro.au"
+MAIL_RECIPIENTS="elspeth@esscc.uq.edu.au" 
 
-echo "PBS_JOBNAME       \$PBS_JOBNAME"
-echo "PBS_JOBID         \$PBS_JOBID"
-echo "PBS_QUEUE         \$PBS_QUEUE"
-echo "NCPUS             \$NCPUS"
-echo "USER              \$USER"
-echo "PBS_O_HOST        \$PBS_O_HOST"
-echo "PBS_O_WORKDIR     \$PBS_O_WORKDIR"
-echo "PBS_O_SHELL       \$PBS_O_SHELL"
-echo ""
-echo ""
+# the python tests to run
+BRUCE_PYTESTS="ImportTest.passed BruceTest.passed test_utilOnBruce.py"
+ESCRIPT_PYTESTS="ImportTest.passed BinaryOps.passed UnaryOps.passed SliceGetting.passed SliceSetting.passed MiscTests.passed ArchiveTests.passed newEscriptTests.passed test_xml.passed insituTests.passed s2.passed"
+FINLEY_PYTESTS="ImportTest.passed finleyTest.passed SimpleSolve.passed RecTest.passed test_linearPDEsOnFinley.passed test_generators.passed test_visualization_interface.passed test_utilOnFinley.passed"
 
+# Changed slightly to cope with new script, so it doesn't stomp all over previous iterations
 
+echo "===> cd $1"
+cd $1
+if [ $? != 0 ]
+then
+  echo "couldnt cd $1"
+  echo "couldnt cd $1" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
+  exit 1
+fi
 
-START=\`date '+%Y/%m/%d %H:%M'\`
+# this is for the automated script
+echo "===> change up a directory"
+cd ..
+echo "===> make a sandbox and work in that"
+mkdir sandbox
+cd sandbox
 
-finish () {
-  END=\`date '+%Y/%m/%d %H:%M'\`
-  cat << END_MSG | mail -s "ESYS_TESTS $target $RunDate \$1" $MAIL_RECIPIENTS
-\$2.
-The tests ran from \$START to \$END.
-See the log files in $WorkDir/Logs for more information.
-This mail was sent by $SCRIPT_NAME
-running as \$USER on \`hostname\`.
-END_MSG
-  test "x$1" = "FAIL" && exit 1
-  exit 0
-}
+PWD=`pwd`
+echo "===> working in: $PWD"
 
-
-cd $WorkDir				|| finish FAILURE "Could not cd to WorkDir $WorkDir"
-
-# Create an empty out_file
-cat /dev/null > $out_file		|| finish FAILURE "Could not create out_file $out_file"
-
-umask 022
-
-test -d sandbox.$RunDate		&& finish FAILURE "Today's sandbox already exists"
-mkdir sandbox.$RunDate			|| finish FAILURE "Could not mkdir sandbox"
-cd sandbox.$RunDate			|| finish FAILURE "Could not cd to sandbox"
-
-echo "Checking out esys13/trunk"
-svn checkout svn+ssh://shake200.esscc.uq.edu.au/home/www_svn/repos/esys13/trunk >> $out_file 2>&1 || finish FAILURE "Could not check out esys13/trunk"
-
-# Load modules
-. /opt/modules/default/init/bash
-module use /raid2/matt/modules/modulefiles
-module use /raid2/toolspp4/modulefiles/gcc-3.3.6
-module use /usr/share/modules/modulefiles
-module load esys/env	# Matt's recommended modules
-module load doxygen/1.4.6
-# The next line is to avoid /raid3/ksteube/AutoTests/sandbox.2006_06_17/trunk/build/posix/bruce/test/bruce_UnitTest: error while loading shared libraries: libboost_python-mt-d.so.1.33.0: cannot open shared object file: No such file or directory
+# Setup the environment
+echo "loading modules"
+. ${MODULESHOME}/init/sh
+module load intel_cc.9.0.026
+export MODULEPATH=${MODULEPATH}:/data/raid2/toolspp4/modulefiles/gcc-3.3.6
+module load python/2.4.1
 module load boost/1.33.0/python-2.4.1
+module load numarray/1.3.3
 
+# set openmp settings
+export OMP_NUM_THREADS=4
 
-# Had to request 2 CPUs, but only use one for the tests
-export OMP_NUM_THREADS=1
+# doesn't appear to work - don't know why.
+#echo "===> svn update"
+#svn update
+#if [ $? != 0 ]
+#then
+#  echo "svn update failed"
+#  echo "svn update failed" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
+#  exit 2
+#fi
 
-# Run the tests
-echo "Running the tests"
-cd trunk				|| finish FAILURE "Could not cd to trunk"
-scons $target >> $out_file 2>&1		|| finish FAILURE "Could not run scons $target"
+# Need to test this bit yet.
+echo "==> removing previous checkout"
+rm -rf trunk/
+ls
+# This works - temporarily removed to speed up testing.
+echo "==> svn checkout"
+svn checkout svn+ssh://ess/esys13/trunk
+if [ $? != 0 ]
+then
+    echo "svn checkout failed"
+    echo "svn checkout failed" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
+    exit 2
+fi
 
-# Delete files older than 21 days
-find $WorkDir -atime +21 -exec rm -f {} \;
+echo "==> change to trunk"
+ls trunk
+cd trunk
 
-# Clean up the sandbox
-cd $WorkDir				|| finish FAILURE "Could not cd to clean up WorkDir $WorkDir"
-/bin/rm -rf sandbox.$RunDate		|| finish FAILURE "Could not delete sandbox"
+# This bit works. Commented out to speed up testing.
+echo "===> scons building esys"
+scons
+if [ $? != 0 ]
+then
+  echo "scons build failed"
+  echo "scons build failed" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
+  exit 3
+fi
 
-finish SUCCESS "Successfully ran 'scons $target', see Logs in $WorkDir on ess"
+# This bit works. Commented out to speed up testing.
+echo "===> building unit_tests"
+scons build_all_tests
+if [ $? != 0 ]
+then
+  echo "build_tests failed"
+  echo "build_tests failed" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
+  exit 3
+fi
 
-EOF
+FAIL=0
 
-# cd to the logs area so the PBS logs are deposited there
-cd $WorkDir/Logs
-
-# Submit the job
-. /opt/modules/default/init/sh
-module load pbspro
-qsub -S /bin/bash $RunDate.pbs.script.sh > /dev/null
-
+#echo "===> running all tests"
+#scons all_tests 
+if [ $? != 0 ]
+then
+  echo "all_tests failed"
+  echo "all_tests failed" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
+  exit 4
+fi
