Added instructions on how to install debian package to the install guide. Wrapper script generation now produces two scripts (escript and finleypython). The two are identical - eventually we will remove finleypython.
Modified the wrapper script so it will print a message and start the python interpreter if you don't specify a script.

diff --git a/scripts/finley_wrapper_template b/scripts/finley_wrapper_template
--- a/scripts/finley_wrapper_template
+++ b/scripts/finley_wrapper_template
@@ -67,9 +67,10 @@ shift `expr $OPTIND - 1`
 
 # Must have at least one command-line arg: the python script
 if [ $# -eq 0 ]; then
-  echo "Missing python script"
-  echo "$HELP_TEXT"
-  exit 1
+  echo "No python script specified. Starting python interpreter."
+#   echo "Missing python script"
+#   echo "$HELP_TEXT"
+#   exit 1
 fi
 
 # Using OpenMP?
