more escript wrapper stuff

diff --git a/trunk/scripts/finley_wrapper_template b/trunk/scripts/finley_wrapper_template
--- a/trunk/scripts/finley_wrapper_template
+++ b/trunk/scripts/finley_wrapper_template
@@ -17,6 +17,8 @@ CURDIR=`pwd`
 #Environment vars which control operations:
 # ESCRIPT_NUM_NODES, ESCRIPT_NUM_PROC, ESCRIPT_NUM_THREADS, ESCRIPT_HOSTFILE, ESCRIPT_CREATESTDFILES
 
+HOSTFILE=/tmp/escript.$$
+
 
 #Need to match if the name contains /
 if [[ $0 =~ / ]]
@@ -44,6 +46,7 @@ cd $CURDIR
 ##### End finding ESCRIPT_ROOT  ########
 
 PYTHON_MPI="$ESCRIPT_ROOT/lib/pythonMPI"
+PYTHON_CMD=python
 
 # if possible please express paths relative to $ESCRIPT_ROOT unless
 # they are in an unrelated location
@@ -190,23 +193,54 @@ then
     then
         echo "Warning: MPI disabled but number of processors per node set. Option ignored."
     fi
+    if [ ! -z $ESCRIPT_HOSTFILE ]
+    then
+        echo "Warning: MPI disabled but host file is given. Option ignored."
+    fi
     ESCRIPT_NUM_NODES=1
     ESCRIPT_NUM_PROCS=1
 else
+    if [ ! -z $ESCRIPT_HOSTFILE ] 
+    then
+        if [ -f $ESCRIPT_HOSTFILE ]
+        then
+            cat $ESCRIPT_HOSTFILE | sort -u > $HOSTFILE
+            NUM_HOSTS = `wc -l $HOSTFILE`
+            if [ ! -z $ESCRIPT_NUM_NODES ] 
+            then
+                if [ $NUM_HOSTS -ne $ESCRIPT_NUM_NODES ]
+                then
+                    echo "number of hosts selected in the host file $ESCRIPT_HOSTFILE needs to match the requested number of nodes $ESCRIPT_NUM_NODES."
+                    exit 1
+                fi
+             else
+                ESCRIPT_NUM_NODES = $NUM_HOSTS
+             fi
+        else
+           echo "cannot find hostfile $ESCRIPT_HOSTFILE."
+           exit 1
+        fi
+    else
+        HOSTFILE=''
+    fi
+
     if [ -z $ESCRIPT_NUM_NODES ]
     then
       ESCRIPT_NUM_NODES=1
     fi
+
     if [ -z $ESCRIPT_NUM_PROCS ]
     then
       ESCRIPT_NUM_PROCS=1
     fi
+
     if [ ! -z $ESCRIPT_VERBOSE  ]
     then 
           echo "ESCRIPT_NUM_NODES = $ESCRIPT_NUM_NODES "
           echo "ESCRIPT_NUM_PROCS = $ESCRIPT_NUM_PROCS "
     fi
 fi
+
 if [ ! -z $ESCRIPT_WITH_OPENMP ]
 then
    if [ -z $ESCRIPT_NUM_THREADS ]
@@ -239,16 +273,24 @@ then
   exit 1
 fi
 #=========================================================================================================
+# Must have at least one command-line arg: the python script
+if [ $# -eq 0 ]
+then
+  if [ ! -z $DOBINARY ]
+  then
+    echo "No program to run was specified. Exiting."
+    exit 1
+  fi
+fi
+
+#=========================================================================================================
 if [ ! -z $DOBINARY ]
 then
-    PYTHON_CMD=""
+    EXEC_CMD="$@"
 else
-    PYTHON_CMD=python
-    if [ $TOTPROC -gt 1 ] 
+    if [ $MPI_FLAVOUR  == "none" ]
     then
-        PYTHON_CMD="$PYTHONMPI $@"
-    else
-        # Check to see if the python version we were compiled with matches the one of PYTHON_CMD
+        # Check to see if the python version we were compiled with matches the one of EXEC_CMD
         # We should only do this check if they are running a python script
         if [ -f $ESCRIPT_ROOT/lib/pyversion ]
         then
@@ -263,23 +305,15 @@ else
         fi
 	if [ ! -z $DOINTERACTIVE ]
         then
-           PYTHON_CMD="python -i $@"
+           EXEC_CMD="$PYTHON_CMD -i $@"
         else
-           PYTHON_CMD="python $@"
+           EXEC_CMD="$PYTHON_CMD $@"
         fi
+    else
+        EXEC_CMD="$PYTHONMPI $@"
     fi
-    if [ ! -z $ESCRIPT_VERBOSE ]; then echo "Python command is $PYTHON_CMD."; fi
 fi
-#=========================================================================================================
-# Must have at least one command-line arg: the python script
-if [ $# -eq 0 ]
-then
-  if [ ! -z $DOBINARY ]
-  then
-    echo "No program to run was specified. Exiting."
-    exit 1
-  fi
-fi
+if [ ! -z $ESCRIPT_VERBOSE ]; then echo "Command to be executed is $EXEC_CMD."; fi
 #===============================================================================================
 #
 #   now we start to spwan things:
@@ -292,16 +326,24 @@ fi
 
 if [ $MPI_FLAVOUR  == "none" ] 
 then
-   $PYTHON_CMD 
+   $EXEC_CMD 
 elif [ $MPI_FLAVOUR == "OPENMPI" ] 
 then 
    echo "OPENMPI not implemented yet."
 
-elif [ $MPI_FLAVOR == "MLP" ]
+elif [ $MPI_FLAVOR == "MPT" ]
 then
    export MPI_NUM_MEMORY_REGIONS=0
-   echo "MLP not implemented yet."
-
+   EXPORT_ENV="$EXPORT_ENV, MPI_NUM_MEMORY_REGIONS"
+   if [ -z $HOSTFILE ] 
+   then
+      HOST_LIST=`awk 'BEGIN{S=""}{if (S == "") { S = $0 } else {S = S "," $0}}END{print S}' $HOSTFILE`
+      CMD="mpiexec $HOST_LIST $ESCRIPT_NUM_PROCS $EXEC_CMD"
+   else
+      CMD="mpiexec -np $TOTPROC -$EXEC_CMD"
+   fi 
+   if [ ! -z $ESCRIPT_VERBOSE ]; then echo "MPI command is $CMD."; fi
+   $CMD
 elif [ $MPI_FLAVOR == "MPICH" ]
 then
    echo "MPICH not implemented yet."
@@ -313,14 +355,14 @@ exit 0
 # Using OpenMP?
 #OMP_OPTIONS=''
 #if [ -f "$ESCRIPT_ROOT/lib/Compiled.with.openmp" ]; then
-#  PYTHON_CMD="$mpi_launcher $MPI_NUM_PROCS $PYTHON_MPI"
+#  EXEC_CMD="$mpi_launcher $MPI_NUM_PROCS $PYTHON_MPI"
 #  ESCRIPT_NUM_THREADS=$OMP_NUM_THREADS
 #  OMP_OPTIONS="env OMP_NUM_THREADS=$ESCRIPT_NUM_THREADS"
 #fi
 
 # Using MPI?
 #if [ -f "$ESCRIPT_ROOT/lib/Compiled.with.mpi" ]; then
-#  PYTHON_CMD="$mpi_launcher $MPI_NUM_PROCS $PYTHON_MPI"
+#  EXEC_CMD="$mpi_launcher $MPI_NUM_PROCS $PYTHON_MPI"
 #else
 #  if [ "$TOTPROC" -ne 1 ]; then
 #    echo "Escript/Finley was not compiled for MPI. You can not use the -n and -p options."
