small fix for the case n=1 under mpi

diff --git a/trunk/bin/escript b/trunk/bin/escript
--- a/trunk/bin/escript
+++ b/trunk/bin/escript
@@ -401,16 +401,22 @@ then
       else 
           if [ ! -z $ESCRIPT_VERBOSE ]; then echo "mpdboot was started with host file $ESCRIPT_HOSTFILE for $ESCRIPT_NUM_NODES nodes."; fi
       fi
+   else
+      mpdboot -n 1 -r ssh 
+      if [ $? -ne 0 ] 
+      then
+         echo "mpdboot failed."
+         exit 1
+      else 
+          if [ ! -z $ESCRIPT_VERBOSE ]; then echo "mpdboot was started."; fi
+      fi
    fi
    CMD="mpiexec -perhost $ESCRIPT_NUM_PROCS -envall -n $TOTPROC $EXEC_CMD"
    if [ ! -z $ESCRIPT_VERBOSE ]; then echo "MPI command is \"$CMD\"."; fi
    $CMD
    EXIT_CODE=$?
-   if [ ! -z $HOSTFILE ]
-   then
-       mpdallexit
-       if [ ! -z $ESCRIPT_VERBOSE ]; then echo "mpdallexit executed."; fi
-   fi 
+   mpdallexit
+   if [ ! -z $ESCRIPT_VERBOSE ]; then echo "mpdallexit executed."; fi
 #=============== SGI's MPIMPT ===================================
 elif [ "$MPI_FLAVOUR" = "MPT" ]
 then
@@ -419,7 +425,7 @@ then
    if [ ! -z $HOSTFILE ] 
    then
       HOST_LIST=`awk 'BEGIN{S=""}{if (S == "") { S = $0 } else {S = S "," $0}}END{print S}' $HOSTFILE`
-      CMD="mpirun $HOST_LIST $ESCRIPT_NUM_PROCS $EXEC_CMD"
+      CMD="mpirun $HOST_LIST -np $ESCRIPT_NUM_PROCS $EXEC_CMD"
    else
       CMD="mpirun -np $TOTPROC $EXEC_CMD"
    fi 
@@ -453,16 +459,22 @@ then
          else 
              if [ ! -z $ESCRIPT_VERBOSE ]; then echo "mpdboot was started with host file $ESCRIPT_HOSTFILE for $ESCRIPT_NUM_NODES nodes."; fi
          fi
+   else
+      mpdboot -n 1 -r ssh 
+      if [ $? -ne 0 ] 
+      then
+         echo "mpdboot failed."
+         exit 1
+      else 
+          if [ ! -z $ESCRIPT_VERBOSE ]; then echo "mpdboot was started."; fi
+      fi
    fi
    CMD="mpiexec -genvlist $EXPORT_ENV -np $TOTPROC $EXEC_CMD"
    if [ ! -z $ESCRIPT_VERBOSE ]; then echo "MPI command is \"$CMD\"."; fi
    $CMD
    EXIT_CODE=$?
-   if [ ! -z $HOSTFILE ]
-   then
-       mpdallexit
-       if [ ! -z $ESCRIPT_VERBOSE ]; then echo "mpdallexit executed."; fi
-   fi 
+   mpdallexit
+   if [ ! -z $ESCRIPT_VERBOSE ]; then echo "mpdallexit executed."; fi
 else
    echo "unknown MPI flavour '$MPI_FLAVOUR'."
 fi
